const page = location.pathname.split('/').pop() || 'index.html';
const active = (name) => page === name ? 'active' : '';
document.querySelector('#header').innerHTML = `<div class="site-header ${page !== 'index.html' ? 'fixed' : ''}"><a class="logo" href="/">AUREN<small>GEBÄUDETECHNIK</small></a><nav class="nav" aria-label="Hauptnavigation"><a class="${active('leistungen.html')}" href="/leistungen.html">Leistungen</a><a class="${active('referenzen.html')}" href="/referenzen.html">Referenzen</a><a class="${active('unternehmen.html')}" href="/unternehmen.html">Unternehmen</a><a class="${active('kontakt.html')}" href="/kontakt.html">Kontakt</a></nav><a class="header-cta" href="/kontakt.html#konfigurator">Projekt konfigurieren ↗</a><button class="menu-btn" aria-label="Menü öffnen" aria-expanded="false">☰</button></div>`;
document.querySelector('#footer').innerHTML = `<div class="site-footer"><div class="footer-top"><div><a class="logo" href="/">AUREN<small>GEBÄUDETECHNIK</small></a></div><div><h4>Kontakt</h4><a href="tel:+493412647390">+49 341 264 73 90</a><a href="mailto:projekt@auren-technik.de">projekt@auren-technik.de</a></div><div><h4>Standort</h4><p>Naumburger Straße 28<br>04229 Leipzig</p></div><div><h4>Navigation</h4><a href="/leistungen.html">Leistungen</a><a href="/referenzen.html">Referenzen</a><a href="/unternehmen.html">Unternehmen</a></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} AUREN Gebäudetechnik GmbH</span><span>Impressum &nbsp; Datenschutz</span></div></div>`;
const menu = document.querySelector('.menu-btn'), nav = document.querySelector('.nav');
menu.addEventListener('click',()=>{nav.classList.toggle('open');document.body.classList.toggle('menu-open');menu.textContent=nav.classList.contains('open')?'×':'☰';menu.setAttribute('aria-expanded',nav.classList.contains('open'))});
const io = new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});
document.querySelectorAll('main section:not(.hero):not(.page-hero)').forEach(el=>{el.classList.add('reveal');io.observe(el)});

const form=document.querySelector('#project-form');
if(form){form.addEventListener('submit',e=>{e.preventDefault();form.querySelectorAll('.error').forEach(x=>x.remove());let ok=true;[['name','Bitte nennen Sie uns Ihren Namen.'],['email','Bitte geben Sie eine gültige E-Mail-Adresse ein.'],['message','Bitte beschreiben Sie Ihr Projekt kurz.']].forEach(([id,msg])=>{const f=form.elements[id];if(!f.value.trim()||(id==='email'&&!/^\S+@\S+\.\S+$/.test(f.value))){const er=document.createElement('div');er.className='error';er.textContent=msg;f.after(er);ok=false}});if(ok){form.innerHTML='<div class="success"><h3>Vielen Dank für Ihre Anfrage.</h3><p>Wir prüfen Ihre Angaben und melden uns in der Regel innerhalb eines Werktags persönlich bei Ihnen.</p></div>';form.scrollIntoView({behavior:'smooth',block:'center'})}})}

const config=document.querySelector('#configurator');
if(config){let step=0;const choices={};const steps=[...config.querySelectorAll('.config-step')];const show=()=>{steps.forEach((s,i)=>s.classList.toggle('active',i===step));config.querySelectorAll('.config-progress i').forEach((x,i)=>x.classList.toggle('on',i<=step))};config.querySelectorAll('.option').forEach(btn=>btn.onclick=()=>{if(btn.dataset.multi==='true'){btn.classList.toggle('selected');choices[btn.dataset.key]=[...btn.parentElement.querySelectorAll('.selected')].map(x=>x.textContent)}else{btn.parentElement.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');choices[btn.dataset.key]=btn.textContent}});config.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>{if(step<steps.length-1){step++;show();if(step===steps.length-1){config.querySelector('.config-summary').innerHTML=Object.entries(choices).map(([k,v])=>`<div><b>${k}</b><br>${Array.isArray(v)?v.join(', '):v}</div>`).join('');localStorage.setItem('aurenConfig',JSON.stringify(choices))}}});config.querySelectorAll('[data-prev]').forEach(b=>b.onclick=()=>{step=Math.max(0,step-1);show()});show()}
if(form){try{const c=JSON.parse(localStorage.getItem('aurenConfig'));if(c){form.elements.message.value=`Projekt-Konfiguration:\n${Object.entries(c).map(([k,v])=>`${k}: ${Array.isArray(v)?v.join(', '):v}`).join('\n')}\n\nWeitere Angaben: `}}catch{}}
